server:
  port: 8090
  servlet:
    context-path: /api/v1

spring:
  application:
    name: bestcommerce-signup-ms

  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

management:
  endpoints:
    web:
      exposure:
        include: '*'